server:
  port: 6868

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 30
  server:
    enable-self-preservation: false  # dev 关闭自我保护

spring:
  security:
    user:
      name: user1
      password: password2


