server:
  port: 8081

spring:
  application:
    name: item-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://user1:password2@localhost:6868/eureka/
    register-with-eureka: true