server:
  port: 8085

spring:
  application:
    name: item-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          zk-nodes:
          min-partition-count: 1
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        testa:
          destination: test_spring_stream
          group: item-service
          consumer:
            concurrency: 1
            partitioned: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://user1:password2@localhost:6868/eureka/
    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 40
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS