server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://cxytiandi.com
        predicates:
        - Path=/course

