server:
  port: 8086

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          zk-nodes:
          min-partition-count: 1
          auto-create-topics: true
          auto-add-partitions: true
      bindings:
        sourceA:
          destination: test_spring_stream
          producer:
            partitionCount: 1
  data:
    mongodb:
      host: 10.72.8.97
      port: 27017
      database: app

eureka:
  client:
    serviceUrl:
      defaultZone: http://user1:password2@localhost:6868/eureka/
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS