server:
  port: 8083

spring:
  application:
    name: order-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        percentage: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://user1:password2@localhost:6868/eureka/
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /
